name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout (Mac)
        if: runner.os == 'macOS'
        uses: actions/checkout@v4

      - name: Checkout (Windows Bypass)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p /d/build-source
          cd /d/build-source
          git clone https://github.com/emxDEV/core-trading-platform..git .
          git checkout ${{ github.sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cd /d/build-source && npm install
          else
            npm install
          fi
        shell: bash

      - name: Build and Publish
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cd /d/build-source && npm run electron:build -- --publish always
          else
            npm run electron:build -- --publish always
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
